-- Insert sample users
INSERT INTO td_users (full_name, email, password) VALUES
('Ivan Petrov', 'ivan.petro@gmail.com', '$2a$10$TQx3DpMlD7Wb75lgMZT8tH1hxhMOwdGh3H6rh/KT6bQ03DOp7Q/KC'),
('Maria Dimitrova', 'maria.dim@gmail.com', '$2a$10$7UAY0gX1CkM2j3DbyThwD3gHkHkh8Y28re.kFBFYw1Zmfs3oSe9Hm'),
('Georgi Ivanov', 'georgi.ivanov@gmail.com', '$2a$10$WjgpFFpeMZ4t9ZXYjxmtf.CXwIjlMxl6w0Hzeb5pGrlDFh3qvLF5y'),
('Elena Nikolova', 'elena.nikolova@gmail.com', '$2a$10$PtjPpPdbdFu8m1h2tEo/pwVv99i14t0ewYNMLmKhMqe7EZC1lc.lG'),
('Stefan Vasilev', 'stefan.vasilev@gmail.com', '$2a$10$y2cHg8AC5o9fow9Fyvw4j/Gezzdu9Smmt7frtIm0rG/FN5N4aDzVe'),
('Desislava Georgieva', 'desislava.geo@gmail.com', '$2a$10$9x6jzF9z8v5XYpW7HgZ34y6JfiEK1j9zANbM7scgmR43gPi67PYxy'),
('Kristiyan Stoyanov', 'kristiyan.stoyanov@gmail.com', '$2a$10$B7aK6Q5I0YxylWeRM5mCq.QtXK5AsdAlndXrhANZq0Kp0J0rEJK1u'),
('Anton Kolev', 'anton.kolev@gmail.com', '$2a$10$y7czQkXbyuYzkqZFtABGVsiM9Xj9csR9jr.V6VZb0yA56CwSkt67GQ'),
('Petya Todorova', 'petya.todorova@gmail.com', '$2a$10$P32Od9kpAhs4nHFd7odS3kdoDN8FsLOihqYdtJ7HV3B8jMvDd6V.m'),
('Nikolay Angelov', 'nikolay.angelov@gmail.com', '$2a$10$4Hf1XK0ikBt5A23JneXxuReJmZA5zXm3wTtbEGB2pVIfIzPjmPC6S'),
('Katerina Ivanova', 'katerina.ivanova@gmail.com', '$2a$10$DzzjjdkhTQ8N12vjIjx5dK4QwAkbT6t8vUhrh.kCTHlfRrkdoJMiC'),
('Viktor Dimitrov', 'viktor.dimitrov@gmail.com', '$2a$10$PrLxzPfcjmXUy3gOtM2X.kRrPsgZBXbW8k7r/xr98bszzHTZfmIFQ'),
('Anastasia Petrova', 'anastasia.petrova@gmail.com', '$2a$10$Jr5DlrhQ0tQ0XqOGY1O4CvkKlfzcYYNofXZpp8fkrXzrhfq6RPqNK'),
('Yordan Ivanov', 'yordan.ivanov@gmail.com', '$2a$10$XIdVxw2CwmzqE9sYrftlknvvoR5LPxGEF48V9ftJj1ZYF1ztwPCEG'),
('Sofia Koleva', 'sofia.koleva@gmail.com', '$2a$10$A37ScWVGOK7AovPsdWpo1O2EY9MG5Q8wT0Wz5W5W9G1ugRdxNKJUi'),
('Vera Mladenova', 'vera.mladenova@gmail.com', '$2a$10$QZymDZx2v6WZ6mP8d9fXrGV4cIvgt1EjLt94acxKk8TYHL6uTe1kq'),
('Petar Stoyanov', 'petar.stoyanov@gmail.com', '$2a$10$YhOZ8eAqaFhTH8VjKsX6v87r/RVZfLkhNmxpzJ0vcV.W6O5tAHYmG'),
('Elitsa Georgieva', 'elitsa.georgieva@gmail.com', '$2a$10$GFuyv2jt2/xDA1mE7ngfF1u2xGH5kX6grsCZOnT9KHljc97WJ9A1m'),
('Stefan Apostolov', 'stefan.apostolov@gmail.com', '$2a$10$Lg6T02R2ovgfveUu9m18d8A8Siv75bLCvvOZV1snRtql53nC6fFqK'),
('Diana Yordanova', 'diana.yordanova@gmail.com', '$2a$10$Dkd4bhNiRfaOaG3FFu4Jt.S6PkrqI.YqVr0c9mHtLpsb9z3zzGhR2');

-- Insert sample channels
INSERT INTO td_channels (name) VALUES
('General Chat'),
('Tech Discussions'),
('Gaming Room'),
('Movies & TV'),
('Sports Zone'),
('Random Talk'),
('Work & Projects'),
('Music Lovers'),
('Book Club'),
('Fitness Talk');

-- Insert friend invitations (Pending)
INSERT INTO tc_friend_invitations (sender_id, recipient_id) VALUES
(1, 2), (1, 3), (2, 4), (3, 5), (4, 6), (5, 7),
(6, 8), (7, 9), (8, 10), (9, 11), (10, 12), (11, 13),
(12, 14), (13, 15), (14, 16), (15, 17), (16, 18), (17, 19), (18, 20),
(1, 5), (3, 7);

-- Accept friend invitations
UPDATE tc_friend_invitations
SET is_active = 0;

-- Insert friendships
INSERT INTO tc_friendships (user1_id, user2_id) VALUES
(1, 2), (1, 3), (2, 4), (3, 5), (4, 6), (5, 7),
(6, 8), (7, 9), (8, 10), (9, 11), (10, 12), (11, 13),
(12, 14), (13, 15), (14, 16), (15, 17), (16, 18), (17, 19), (18, 20),
(1, 5), (3, 7);

-- Insert channel memberships
INSERT INTO tc_channel_membership (channel_id, user_id, role_id) VALUES
(1, 1, 1), (1, 2, 2), (1, 3, 3), (2, 4, 1), (2, 5, 2),
(3, 6, 1), (3, 7, 3), (4, 8, 2), (4, 9, 3), (5, 10, 1),
(5, 11, 2), (6, 12, 3), (6, 13, 2), (7, 14, 1), (7, 15, 3),
(8, 16, 2), (9, 17, 1);

INSERT INTO td_messages (content, sender_id, channel_id, created_at) VALUES
('Hello everyone, welcome to the General Chat!', 1, 1, TIMESTAMPADD(SECOND, 0, NOW())),
('Lets discuss the latest tech innovations!', 2, 2, TIMESTAMPADD(SECOND, 1, NOW())),
('Who''s excited for the next gaming tournament?', 3, 3, TIMESTAMPADD(SECOND, 2, NOW())),
('Anyone up for a movie marathon tonight?', 4, 4, TIMESTAMPADD(SECOND, 3, NOW())),
('What are your predictions for the Champions League this year?', 5, 5, TIMESTAMPADD(SECOND, 4, NOW())),
('Random question: What is your go-to comfort food?', 6, 6, TIMESTAMPADD(SECOND, 5, NOW())),
('Lets get some work done today, folks!', 7, 7, TIMESTAMPADD(SECOND, 6, NOW())),
('Have you guys seen the new updates to JavaScript?', 1, 2, TIMESTAMPADD(SECOND, 7, NOW())),
('What games are you playing these days?', 2, 3, TIMESTAMPADD(SECOND, 8, NOW())),
('Just watched the latest Marvel movie!', 3, 4, TIMESTAMPADD(SECOND, 9, NOW())),
('I think the new season of the Champions League will be incredible.', 4, 5, TIMESTAMPADD(SECOND, 10, NOW())),
('Anyone know a good productivity app?', 5, 6, TIMESTAMPADD(SECOND, 11, NOW())),
('I need a new book recommendation!', 6, 8, TIMESTAMPADD(SECOND, 12, NOW())),
('Lets catch up on work progress.', 7, 7, TIMESTAMPADD(SECOND, 13, NOW())),
('I am thinking of building my first mobile app, any tips?', 8, 2, TIMESTAMPADD(SECOND, 14, NOW())),
('What is the best workout routine for beginners?', 9, 10, TIMESTAMPADD(SECOND, 15, NOW())),
('I have been reading a lot of sci-fi lately, anyone else?', 10, 9, TIMESTAMPADD(SECOND, 16, NOW())),
('Lets plan a tech meetup soon!', 11, 2, TIMESTAMPADD(SECOND, 17, NOW())),
('What is your favorite tech gadget?', 12, 2, TIMESTAMPADD(SECOND, 18, NOW())),
('Anybody here who loves retro games?', 13, 3, TIMESTAMPADD(SECOND, 19, NOW())),
('Best way to stay motivated during work?', 14, 7, TIMESTAMPADD(SECOND, 20, NOW())),
('What movies have you guys seen recently?', 15, 4, TIMESTAMPADD(SECOND, 21, NOW())),
('Anyone else watching a series these days?', 16, 4, TIMESTAMPADD(SECOND, 22, NOW())),
('The Champions League final was insane!', 17, 5, TIMESTAMPADD(SECOND, 23, NOW())),
('Lets talk about the upcoming book fair.', 18, 8, TIMESTAMPADD(SECOND, 24, NOW())),
('What is your favorite genre of music?', 19, 6, TIMESTAMPADD(SECOND, 25, NOW())),
('Has anyone heard of this new fitness app?', 20, 10, TIMESTAMPADD(SECOND, 26, NOW())),
('What kind of projects are you working on?', 1, 7, TIMESTAMPADD(SECOND, 27, NOW())),
('Should we organize a coding competition?', 2, 7, TIMESTAMPADD(SECOND, 28, NOW())),
('Anyone have tips for a healthy morning routine?', 3, 10, TIMESTAMPADD(SECOND, 29, NOW())),
('How do you all stay productive during a weekend?', 4, 7, TIMESTAMPADD(SECOND, 30, NOW())),
('Anyone here interested in graphic design?', 5, 2, TIMESTAMPADD(SECOND, 31, NOW())),
('What was your first job in tech?', 6, 2, TIMESTAMPADD(SECOND, 32, NOW())),
('Who''s up for an online trivia competition?', 7, 6, TIMESTAMPADD(SECOND, 33, NOW())),
('Anyone watching the new Breaking Bad spin-off?', 8, 4, TIMESTAMPADD(SECOND, 34, NOW())),
('Lets share some fun facts today!', 9, 6, TIMESTAMPADD(SECOND, 35, NOW())),
('What is the best mobile game you’re playing right now?', 10, 3, TIMESTAMPADD(SECOND, 36, NOW())),
('Lets discuss the latest tech podcast.', 11, 2, TIMESTAMPADD(SECOND, 37, NOW())),
('What is your favorite hobby besides tech?', 12, 7, TIMESTAMPADD(SECOND, 38, NOW())),
('Anyone interested in VR games?', 13, 3, TIMESTAMPADD(SECOND, 39, NOW())),
('How is your project going?', 14, 7, TIMESTAMPADD(SECOND, 40, NOW())),
('What app do you use for time management?', 15, 7, TIMESTAMPADD(SECOND, 41, NOW())),
('Does anyone know a good project management tool?', 16, 7, TIMESTAMPADD(SECOND, 42, NOW())),
('I am obsessed with the new Star Wars game, who else?', 17, 3, TIMESTAMPADD(SECOND, 43, NOW())),
('Has anyone tried mindfulness meditation?', 18, 6, TIMESTAMPADD(SECOND, 44, NOW())),
('What is the best meal for a quick lunch?', 19, 6, TIMESTAMPADD(SECOND, 45, NOW())),
('Anyone using any cool productivity hacks?', 20, 7, TIMESTAMPADD(SECOND, 46, NOW())),
('Lets set up a brainstorming session for a new app idea.', 1, 2, TIMESTAMPADD(SECOND, 47, NOW())),
('What is your favorite sports team?', 2, 5, TIMESTAMPADD(SECOND, 48, NOW())),
('What is your current project you’re working on?', 3, 7, TIMESTAMPADD(SECOND, 49, NOW())),
('Anyone into photography?', 4, 2, TIMESTAMPADD(SECOND, 50, NOW())),
('Who loves a good classic movie?', 5, 4, TIMESTAMPADD(SECOND, 51, NOW())),
('What is the best motivational podcast?', 6, 7, TIMESTAMPADD(SECOND, 52, NOW())),
('Can anyone recommend a good startup?', 7, 2, TIMESTAMPADD(SECOND, 53, NOW())),
('Any news on the new Android update?', 8, 2, TIMESTAMPADD(SECOND, 54, NOW())),
('I have just started learning Python. Any tips?', 9, 2, TIMESTAMPADD(SECOND, 55, NOW())),
('What was your first coding language?', 10, 2, TIMESTAMPADD(SECOND, 56, NOW())),
('Anyone up for a weekend project together?', 11, 7, TIMESTAMPADD(SECOND, 57, NOW())),
('Lets have a tech debate on AI vs. human intelligence.', 12, 2, TIMESTAMPADD(SECOND, 58, NOW()));

INSERT INTO td_messages (content, sender_id, recipient_id, created_at) VALUES
('Hey, how is your day going?', 1, 2, TIMESTAMPADD(SECOND, 59, NOW())),
('Did you finish the report?', 3, 4, TIMESTAMPADD(SECOND, 118, NOW())),
('Lets grab coffee tomorrow!', 5, 6, TIMESTAMPADD(SECOND, 177, NOW())),
('Are you free for a call later?', 7, 8, TIMESTAMPADD(SECOND, 236, NOW())),
('I got a new project, need advice!', 9, 10, TIMESTAMPADD(SECOND, 295, NOW())),
('How are you liking the new job?', 11, 12, TIMESTAMPADD(SECOND, 354, NOW())),
('Got some new tech gadgets, want to check them out?', 13, 14, TIMESTAMPADD(SECOND, 413, NOW())),
('What is your favorite game?', 15, 16, TIMESTAMPADD(SECOND, 472, NOW())),
('Have you seen the new documentary on Netflix?', 17, 18, TIMESTAMPADD(SECOND, 531, NOW())),
('I have a great podcast for you!', 19, 20, TIMESTAMPADD(SECOND, 590, NOW())),
('Lets collaborate on this app!', 1, 3, TIMESTAMPADD(SECOND, 649, NOW())),
('What is your opinion on the new iPhone?', 2, 5, TIMESTAMPADD(SECOND, 708, NOW())),
('Are you interested in a coding challenge?', 3, 6, TIMESTAMPADD(SECOND, 767, NOW())),
('Can you give me feedback on my new app idea?', 4, 7, TIMESTAMPADD(SECOND, 826, NOW())),
('Any plans for the weekend?', 5, 10, TIMESTAMPADD(SECOND, 885, NOW())),
('Have you read that new tech blog?', 6, 9, TIMESTAMPADD(SECOND, 944, NOW())),
('What is your favorite productivity tool?', 7, 8, TIMESTAMPADD(SECOND, 1003, NOW())),
('When is the next fitness meetup?', 8, 10, TIMESTAMPADD(SECOND, 1062, NOW())),
('What game are you playing these days?', 9, 3, TIMESTAMPADD(SECOND, 1121, NOW())),
('I am stuck on a bug, can you help?', 10, 4, TIMESTAMPADD(SECOND, 1180, NOW())),
('Are you up for a weekend project?', 11, 13, TIMESTAMPADD(SECOND, 1239, NOW())),
('Lets create a project together!', 12, 14, TIMESTAMPADD(SECOND, 1298, NOW())),
('How do you stay motivated during long hours?', 13, 5, TIMESTAMPADD(SECOND, 1357, NOW())),
('Can you recommend me a good podcast for coding?', 14, 2, TIMESTAMPADD(SECOND, 1416, NOW())),
('Did you finish reading the book I recommended?', 15, 6, TIMESTAMPADD(SECOND, 1475, NOW())),
('Want to join a coding bootcamp together?', 16, 7, TIMESTAMPADD(SECOND, 1534, NOW())),
('I have been thinking about building a new app, what do you think?', 17, 8, TIMESTAMPADD(SECOND, 1593, NOW())),
('Lets organize a tech meetup!', 18, 1, TIMESTAMPADD(SECOND, 1652, NOW())),
('What is the latest book you read?', 19, 15, TIMESTAMPADD(SECOND, 1711, NOW())),
('How do you usually start your workday?', 20, 3, TIMESTAMPADD(SECOND, 1770, NOW())),
('Got any tips on learning new programming languages?', 1, 12, TIMESTAMPADD(SECOND, 1829, NOW())),
('Any favorite TV series you’re binge-watching?', 2, 14, TIMESTAMPADD(SECOND, 1888, NOW())),
('How is your project going?', 3, 17, TIMESTAMPADD(SECOND, 1947, NOW())),
('Lets work on a side project!', 4, 16, TIMESTAMPADD(SECOND, 2006, NOW())),
('Do you prefer working alone or with a team?', 5, 9, TIMESTAMPADD(SECOND, 2065, NOW())),
('I need a good workout playlist, any ideas?', 6, 18, TIMESTAMPADD(SECOND, 2124, NOW())),
('What do you think about the new update?', 7, 11, TIMESTAMPADD(SECOND, 2183, NOW())),
('Lets meet up soon for a project brainstorm.', 8, 19, TIMESTAMPADD(SECOND, 2242, NOW())),
('Can you help me with a coding issue I am facing?', 9, 13, TIMESTAMPADD(SECOND, 2301, NOW())),
('I have got a new idea for a startup, want to discuss?', 10, 15, TIMESTAMPADD(SECOND, 2360, NOW())),
('What is the best tech news source?', 11, 2, TIMESTAMPADD(SECOND, 2419, NOW())),
('Lets discuss ideas for the new app we’re building.', 12, 7, TIMESTAMPADD(SECOND, 2478, NOW())),
('I am considering a career change, what do you think?', 13, 5, TIMESTAMPADD(SECOND, 2537, NOW())),
('Want to join a startup pitch event next week?', 14, 1, TIMESTAMPADD(SECOND, 2596, NOW())),
('How do you handle distractions during work?', 15, 16, TIMESTAMPADD(SECOND, 2655, NOW())),
('I have got some cool coding tools I want to share with you.', 16, 14, TIMESTAMPADD(SECOND, 2714, NOW())),
('Lets exchange book recommendations!', 17, 10, TIMESTAMPADD(SECOND, 2773, NOW()));